apiVersion: v1
kind: Service
metadata: 
  name: axd-web
  labels:
    kube-svc: axd-web
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    kube-app: axd-web

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: axd-web
  labels:
    kube-app: axd-web
spec:
  replicas:  1
  template:
    metadata:
      labels:
        kube-app: axd-web
    spec:
      containers:
      - name: axd-web
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: opt-dir
      volumes:
      - hostPath:
          path: /opt/html
          type: DirectoryOrCreate
        name: opt-dir

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
<<<<<<< HEAD
    traefik.ingress.kubernetes.io/rewrite-target: /
=======
>>>>>>> 2e813ddcca31beebdb95c4db4d28f1e7f855db63
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/preserve-host: "true"
  name: axd-web-ingress
spec:
  rules:
  - host: api.aixiangdao.tech
    http:
      paths:
      - backend:
          serviceName: axd-web
          servicePort: 80
        path: /web
      - backend:
          serviceName: axd-web
<<<<<<< HEAD
          servicePort: 80
=======
          servicePort: 8070
>>>>>>> 2e813ddcca31beebdb95c4db4d28f1e7f855db63
        path: /w3c
