apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: jenkins-ci
  name: jenkins-ci
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jenkins-ci
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-ci
    spec:
      hostNetwork: true
      hostname: iZwz9icc3e3cvfoelmubpxZ
      containers:
      - image: jenkinsci/blueocean
        imagePullPolicy: Always
        name: jenkins-ci
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/run/docker.sock
          name: docker-sock
        securityContext:
          privileged: true
          runAsUser: 0
        #ports:
        #- containerPort: 8080
        #  protocol: TCP
        #- containerPort: 50000
        #  protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - hostPath:
          path: /home/jenkins_home
          type: DirectoryOrCreate
        name: jenkins-home
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-sock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      #securityContext:
      #  privileged: true
      terminationGracePeriodSeconds: 30
