apiVersion: v1
kind: Service
metadata: 
  name: apollo-adminservice
  labels:
    kube-svc: apollo-adminservice
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    kube-app: apollo-adminservice

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apollo-adminservice
  labels:
    kube-app: apollo-adminservice
spec:
  replicas:  1
  revisionHistoryLimit: 
  template:
    metadata:
      labels:
        kube-app: apollo-adminservice
    spec:
      containers:
      - name: apollo-adminservice
        image: registry-vpc.cn-shenzhen.aliyuncs.com/axd/apollo-adminservice:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
