apiVersion: v1
kind: Service
metadata: 
  name: apollo-configservice
  labels:
    kube-svc: apollo-configservice
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    kube-app: apollo-configservice

---
# Source: ack-springcloud-turbine/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apollo-configservice
  labels:
    kube-app: apollo-configservice
spec:
  replicas:  1
  revisionHistoryLimit: 
  template:
    metadata:
      labels:
        kube-app: apollo-configservice
    spec:
      containers:
      - name: apollo-configservice
        image: registry-vpc.cn-shenzhen.aliyuncs.com/axd/apollo-configservice:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
