apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  generation: 3
  labels:
    k8s-app: axd-manager
  name: axd-manager
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: axd-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: axd-manager
    spec:
      containers:
      - command:
        #- /usr/bin/tail
        #- -f
        #- /etc/resolv.conf
        image: registry-vpc.cn-shenzhen.aliyuncs.com/axd/axd-manager-provider:P003
        imagePullPolicy: Always
        name: axd-manager
        ports:
        - containerPort: 1203
          name: http
          protocol: TCP
        resources:
          limits:
            #cpu: "1"
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyun-vpc-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-wz9m85xp1i3fae0u2oxvl
  name: axd-manager-svc
  namespace: default
spec:
  ports:
  - port: 1203
    targetPort: 1203
    name: http
  selector:
    k8s-app: axd-manager
  type: LoadBalancer
