apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  generation: 3
  labels:
    k8s-app: axd-basic
  name: axd-basic
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: axd-basic
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: axd-basic
    spec:
      containers:
      - command:
        - /usr/bin/tail
        - -f
        - /etc/resolv.conf
        image: registry-vpc.cn-shenzhen.aliyuncs.com/axd/axd-basic-provider:P003
        imagePullPolicy: Always
        name: axd-basic
        ports:
        - containerPort: 1201
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyun-vpc-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: axd-basic-svc
  namespace: default
spec:
  ports:
  - port: 1201
    targetPort: 1201
    name: http
  selector:
    k8s-app: axd-basic
  type: NodePort
